#!/bin/bash -e

#app="${1:-/srv/http/app.cgi}"

#sudo true

#deptag # tag this deployment

touch Settings.hs main.hs
cabal install -fproduction --bindir=./

#sudo /etc/rc.d/lighttpd stop
#sudo mv devsite "$app"
#sudo /etc/rc.d/lighttpd start
