#!/bin/bash -ex

if [[ "$1" != 'static' ]]; then
  cabal clean
  cabal configure
  cabal build

  strip dist/build/devsite/devsite
fi

rm -rf static/tmp/

tar czfv - dist/build/devsite/devsite config static > ~/Site/keter/incoming/devsite.keter
