#!/bin/bash -ex

cabal clean
cabal configure
cabal build

strip dist/build/devsite/devsite

rm -rf static/tmp/

tar czfv - dist/build/devsite/devsite config static > ~/Site/keter/incoming/devsite.keter
