#!/bin/bash -e

build() {
  # ensure cpp code-by-macro is up to date
  touch ./Settings.hs             \
        ./Settings/StaticFiles.hs \
        ./Foundation.hs           \
        ./Application.hs

  cabal clean

  if ! cabal configure; then
    cabal install --only-dependencies
    cabal configure
  fi

  cabal build
  cabal check
}

deploy() {
  deptag

  build

  $0 restart
}

start_devsite() {
  local n

  for n in $instances; do
    echo "Starting worker #$n..."
    ./$bin -p 300$n production &> tmp/$n.log &
  done
}

stop_devsite() {
  local pid

  while read -r pid; do
    echo "Stopping worker with pid $pid..."
    if ! kill $pid; then
      kill -9 $pid
    fi
  done < <(pgrep -f "$bin")
}

bin='dist/build/devsite/devsite'

instances='1 2 3'

case "$1" in
  start)   start_devsite  ;;
  stop)    stop_devsite   ;;
  restart) stop_devsite
           sleep 2
           start_devsite  ;;
  build)   build          ;;
  deploy)  deploy         ;;
  *)       exit 1         ;;
esac
