#!/bin/bash -e


usage() { echo 'usage: devsite [ start | stop | deploy ]' >&2; exit 1; }

get_pid() { # {{{
  local n=$1

  if [[ -f tmp/pid/$n.pid ]]; then
    if read -r pid < tmp/pid/$n.pid; then
      if [[ -n $pid ]]; then
        echo $pid
        return 0
      fi
    fi
  fi

  return 1
}
# }}}

deploy_devsite() { # {{{
  deptag;

  # any files with CPP declarations should be touched in case they are
  # out of date.
  touch Settings.hs Application.hs

  cabal clean

  if ! cabal configure; then
    cabal install --only-dependencies
    cabal configure
  fi

  cabal build
  cabal check

  stop_devsite
  sleep 2
  start_devsite
}
# }}}

start_devsite() { # {{{
  local n

  echo 'Starting worker processes...'
  for n in $instances; do
    if pid=$(get_pid $n); then
      if ! ps $pid &>/dev/null; then
        rm -f tmp/pid/$n.pid
      else
        continue
      fi
    fi

    $binary -e production -p 300$n > tmp/log/$n.log 2> tmp/log/$n.errors.log &
    echo $! > tmp/pid/$n.pid
  done
}
# }}}

stop_devsite() { # {{{
  local pid n

  echo 'Stopping worker processes...'
  for n in $instances; do
    if pid=$(get_pid $n); then
      if ps $pid &>/dev/null; then
        ( kill $pid || kill -9 $pid ) &>/dev/null
      fi
    fi

    rm -f tmp/pid/$n.pid
  done
}
# }}}

# experiencing very high memory usage with 7.2, only run one two
# instances for now
#instances='1 2 3 4 5'
instances='1 2'

binary='dist/build/devsite/devsite'

[[ -x "$binary" ]] || { echo 'no binary found!' >&2; exit 1; }

case "$1" in
  start)  start_devsite  ;;
  stop)   stop_devsite   ;;
  deploy) deploy_devsite ;;
  *)      usage          ;;
esac
