#!/bin/bash -e

deploy() {
  deptag;

  touch ./**/*

  cabal clean

  if ! cabal configure; then
    cabal install --only-dependencies
    cabal configure
  fi

  cabal build
  cabal check

  stop_devsite
  sleep 2
  start_devsite
}

start_devsite() {
  local n

  for n in $instances; do
    echo "Staring worker #$n..."
    ./$bin -p 300$n production &> tmp/$n.log &
  done
}

stop_devsite() {
  local pid

  while read r pid; do
    echo "Stopping worker with pid $pid..."
    if ! kill $pid; then
      kill -9 $pid
    fi
  done <(pgrep -f "$bin")
}

bin='dist/build/devsite/devsite'

instances='1 2 3'

case "$1" in
  start)  start_devsite  ;;
  stop)   stop_devsite   ;;
  deploy) deploy_devsite ;;
  *)      usage          ;;
esac
